/** Maps catalog organization names → `/public/org-icons/{slug}.svg`. */
export const ORG_ICON_SLUG: Record<string, string> = {
  OpenAI: "openai",
  Anthropic: "anthropic",
  Google: "google",
  xAI: "xai",
  Meta: "meta",
  DeepSeek: "deepseek",
  Alibaba: "alibaba",
  Mistral: "mistral",
  Moonshot: "moonshot",
  "Zhipu AI": "zhipu",
  Microsoft: "microsoft",
  MiniMax: "minimax",
  Meituan: "meituan",
  NVIDIA: "nvidia",
  Amazon: "amazon",
  Baidu: "baidu",
  ByteDance: "bytedance",
  Cohere: "cohere",
  "01.AI": "yi",
  Ai2: "ai2",
  Cursor: "cursor",
  AI21: "ai21",
  "Arcee AI": "arcee",
  IBM: "ibm",
  "Liquid AI": "liquid",
  Perplexity: "perplexity",
  Snowflake: "snowflake",
  StepFun: "stepfun",
  TII: "tii",
  Upstage: "upstage",
  "Shanghai AI Lab": "internlm",
  Tencent: "tencent",
  "Black Forest Labs": "bfl",
  Ideogram: "ideogram",
  Recraft: "recraft",
  Midjourney: "midjourney",
  "Stability AI": "stability",
  Adobe: "adobe",
  Reve: "reve",
  "Kling AI": "kling",
  Runway: "runway",
  "Luma AI": "luma",
  Lightricks: "lightricks",
  "Skywork AI": "skywork",
  Vidu: "vidu",
  PixVerse: "pixverse",
  Pika: "pika",
  Haiper: "haiper",
};

/** Mono SVGs that use currentColor — render via CSS mask so they track theme. */
export const MONO_ORG_ICONS = new Set([
  "openai",
  "anthropic",
  "xai",
  "cursor",
  "bfl",
  "ideogram",
  "recraft",
  "midjourney",
  "runway",
  "luma",
  "lightricks",
  "pika",
  "haiper",
  "reve",
  "ai21",
  "ibm",
  "liquid",
]);

export function orgIconSlug(organization: string): string | undefined {
  return ORG_ICON_SLUG[organization];
}
